import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import './globals.css';
import Header from './layout/header/Header';
import Sidebar from './layout/sidebar/Sidebar';
import Footer from './layout/footer/Footer';
import { LayoutProps } from '../../../.next/types/app/(site)/layout';
import styles from './layout.module.css';

const notoSans = Noto_Sans_KR({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Next.JS App Project',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Header />
        <div className={styles.layout}>
          <Sidebar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}

